name: branch

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: install pug & build
        run: |
          npm install pug-cli -g
          pug --pretty -o site/bipsi --basedir src -- src/index.pug
      - name: upload page
        uses: actions/upload-artifact@v4
        with:
          name: bipsi.html
          path: ./site/bipsi/index.html
