name: publish

on: [push]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: install pug & build
        run: |
          npm install pug-cli -g
          pug --pretty -o site/bipsi --basedir src -- src/index.pug
      - name: upload github pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./site/bipsi
      - name: deploy to neocities
        uses: bcomnes/deploy-to-neocities@v2
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: false
          dist_dir: ./site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v1
