name: publish

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: install pug-cli & build
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install pug-cli -g
      - run: pug --pretty -o dist --basedir src -- src/index.pug
